# Generated by Django 5.2.2 on 2025-08-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appointment_bill_treatmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='spicialzaton',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
