# Generated by Django 5.2.2 on 2025-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_patient_address_patient_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personal_patient_image',
            field=models.ImageField(blank=True, upload_to='patient_images'),
        ),
    ]
