# Generated by Django 5.2.2 on 2025-08-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_patient_personal_patient_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='personal_patient_image',
            new_name='personal_photo',
        ),
    ]
