# FILE: configs/binary/02_glaucoma.yaml
imports: {path: configs/binary/base_binary_config.yaml}
binary_task:
  disease_name: "Glaucoma"
  positive_keywords: ["glaucoma"]
preprocessing:
  preprocessing_strategy: "GlaucomaPreprocessing"
artifacts: {run_name: "glaucoma_resnet50_v1"}