# FILE: configs/binary/06_myopia.yaml
imports: {path: configs/binary/base_binary_config.yaml}
binary_task:
  disease_name: "Pathological Myopia"
  positive_keywords: ["myopia"]
preprocessing:
  preprocessing_strategy: "PathologicalMyopiaPreprocessing"
artifacts: {run_name: "myopia_resnet50_v1"}