# Generated by Django 5.2.2 on 2025-07-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosis_physician_alter_diagnosis_patient'),
        ('users', '0006_appointment_bill_treatmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis', to='users.appointment'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='medical_notes',
            field=models.TextField(blank=True),
        ),
    ]
