# Generated by Django 5.2.2 on 2025-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_diagnosis_appointment_diagnosis_medical_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when processing finished', null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when processing started', null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='worker_id',
            field=models.CharField(blank=True, help_text='Celery task ID processing this diagnosis', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RETRY', 'Retry'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
